### ISSUE TITLE
Script fetches private IPv4 addresses instead of public ones

### ISSUE THREAD

**Issue by imchairmanm** [kamaln7/do-ssh-alias#1]
:wave: Hey Kamal! :smile: 

Saw this in the yearly wrap up and thought I'd give it a go.

As [someone mentioned in a blog comment](https://www.digitalocean.com/blog/use-do-ssh-alias-for-easier-droplet-ssh-access/?#comment-4987354965), it looks like the API query is now returning private IPv4 addresses.  Works fantastic otherwise!

**Comment by kamaln7** [comment]
Hey Justin! 👋🏼 Sorry, I entirely missed this and only now noticed it. Thanks for letting me know—I'll take a look!

**Comment by kamaln7** [comment]
Just pushed a fix for this 👍🏼

**Comment by imchairmanm** [comment]
Yay! I totally missed your messages too lol.  We're so good at GitHub!

Thanks Kamal!
